### ISSUE TITLE
NPE while updating classpath

### ISSUE THREAD

**Issue by vhdirk** [fwcd/vscode-kotlin#110]
### Description
Not sure how to reproduce it, but I keep getting the following NPE on a hybrid java/kotlin project.

```
Nov 22, 2022 3:09:06 P.M. org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.jsonrpc.messages.Tuple$Two.getFirst()" because "modelAndProjectInfoAndCancelChecker" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.jsonrpc.messages.Tuple$Two.getFirst()" because "modelAndProjectInfoAndCancelChecker" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.jsonrpc.messages.Tuple$Two.getFirst()" because "modelAndProjectInfoAndCancelChecker" is null
	at org.eclipse.lsp4mp.ls.properties.PropertiesFileTextDocumentService.lambda$definition$8(PropertiesFileTextDocumentService.java:198)
	... 10 more
```

### Extension version
v0.2.26

**Comment by themkat** [comment]
Are there any more to the stack trace? It says "... 10 more", is that cut off by you or the language server? Would be nice to have more to see where in the language server this happens.

**Comment by vhdirk** [comment]
That's a cutoff by the language server itself, unfortunately. Is there any parameter I can tweak to get a longer stacktrace? Then I can apply that and wait for it to happen again.

**Comment by themkat** [comment]
@vhdirk , not that I know of. Is this during the initialization of the server? Or does it happen at random times afterwards? Is it a closed source project? Or something you can share? 

Also, does it affect the usage? Or does everything still work even when you get this NPE? The language server currently will print a lot of stack traces in some projects, especially with the hover functionality (some parts it can't get any meaningful information about). Those are usually of the `UnsupportedOperationException`-variety though. Some of it should probably not be printed all the time, as it is just confusing the users 🙁
