### ISSUE TITLE
Kotlin Language Client client: couldn't create connection to server.

### ISSUE THREAD

**Issue by sova32** [fwcd/vscode-kotlin#127]
### Description
install and create new project by gradle init
### Extension version
v0.2.31

### Additional context
![Screenshot_08_08_2023_17_31_56](https://github.com/fwcd/vscode-kotlin/assets/78994014/005fdf89-4600-479d-aa80-05f3e174a1d9)

**Comment by sova32** [comment]
sorry but your plugin is broken

**Comment by sova32** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
авг. 08, 2023 5:46:55 PM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint lambda$recursiveFindRpcMethods$2
SEVERE: A delegate object is null, jsonrpc methods of 'public default org.eclipse.lsp4j.services.NotebookDocumentService org.eclipse.lsp4j.services.LanguageServer.getNotebookDocumentService()' are ignored
[Info  - 17:46:56] main      Adding script definitions [null]
[Info  - 17:46:56] main      Kotlin Language Server: Version 1.3.3
[Error - 17:46:56] main      A delegate object is null, jsonrpc methods of 'public default org.eclipse.lsp4j.services.NotebookDocumentService org.eclipse.lsp4j.services.LanguageServer.getNotebookDocumentService()' are ignored
[Info  - 17:46:56] main      Connected to client
[Info  - 17:46:56] async0    Adding workspace folder proj1
авг. 08, 2023 5:46:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: Bad escape
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Bad escape
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:88)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:102)
	at java.base/java.nio.file.Path.of(Path.java:203)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:70)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda$2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 17:46:56] async0    Internal error: java.lang.IllegalArgumentException: Bad escape
[Error - 17:46:56] java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
[Error - 17:46:56] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[Error - 17:46:56] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[Error - 17:46:56] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[Error - 17:46:56] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Error - 17:46:56] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Error - 17:46:56] 	at java.base/java.lang.Thread.run(Thread.java:833)
[Error - 17:46:56] Caused by: java.lang.IllegalArgumentException: Bad escape
[Error - 17:46:56] 	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:88)
[Error - 17:46:56] 	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:102)
[Error - 17:46:56] 	at java.base/java.nio.file.Path.of(Path.java:203)
[Error - 17:46:56] 	at java.base/java.nio.file.Paths.get(Paths.java:98)
[Error - 17:46:56] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
[Error - 17:46:56] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:70)
[Error - 17:46:56] 	at org.javacs.kt.util.AsyncExecutor.compute$lambda$2(AsyncExecutor.kt:19)
[Error - 17:46:56] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[Error - 17:46:56] 	... 3 more
[Error - 17:46:56] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Bad escape
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:88)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:102)
	at java.base/java.nio.file.Path.of(Path.java:203)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:70)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda$2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 17:46:56] Kotlin Language Client client: couldn't create connection to server.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Bad escape
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:88)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:102)
	at java.base/java.nio.file.Path.of(Path.java:203)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:70)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda$2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

**Comment by themkat** [comment]
Instead of spamfucking comments (some of us receive emails for every one of them), maybe collect them into a few. You can edit to give more context you know.

> sorry but your plugin is broken

This does not give @fwcd or anyone else any information. It is just you complaining about something given to you for free 😛 Nothing is perfect, especially a plugin that very few people contribute to. Comments like yours probably don't give anyone motivation to do so either... 

---

Can you give some useful context?
- Java version. Number + distribution (e.g, Adoptium, Coretto etc.)
- Kotlin version? Any local install? Or just the one included with Gradle?
- Any weird unicode characters in the project path? Almost seems to be that this might be the culprit, based upon the "Bad escape"-errors above. Known issue: https://github.com/fwcd/kotlin-language-server/issues/317

**Comment by sova32** [comment]
Firstly, I did not use offensive language towards you.

Secondly:
When I was creating the bug report, it was not mentioned that I should
provide you with the Java version. Number + distribution (e.g., Adoptium,
Coretto, etc.) Kotlin version, and any local install.

[image: image.png]

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
***@***.*** ~> java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode,
sharing)
***@***.*** ~> kotlin --version
error: unknown option: --version
***@***.*** ~ [1]> kotlin
Welcome to Kotlin version 1.9.0 (JRE 17.0.8+9-LTS-211)
Type :help for help, :quit for quit
>>> :quit
***@***.*** ~> gradle -v

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 16:30:34 UTC
Revision:     <unknown>

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8 (Oracle Corporation 17.0.8+9-LTS-211)
OS:           Linux 6.4.8-zen1-1-zen amd64

***@***.*** ~>


no unicode:
[image: image.png]

i was see this issuise:  fwcd/kotlin-language-server#317
<https://github.com/fwcd/kotlin-language-server/issues/317>

Operating System: Garuda Linux
KDE Plasma Version: 5.27.7
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.8-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 2 × AMD A4-6300 APU with Radeon(tm) HD Graphics
Memory: 13.6 ГиБ of RAM
Graphics Processor: AMD ARUBA

вт, 8 авг. 2023 г. в 18:45, Marie Katrine Ekeberg ***@***.***

**Comment by themkat** [comment]
> Firstly, I did not use offensive language towards you.

You did not use offensive language, and I never said so. I just suggested you were rude. You should be a bit more humble when people help you for free. Would not hurt at all. You take friendly suggestions in the worst way possible... 

> ...
> no unicode:
> [image: image.png]

Okay... No image shown. Still I see cyrilic or something in your mail (when I make an effort to click the ... to show more details). "вт, 8 авг. 2023 г. в " is seen. Are you absolutely sure no special characters, spaces or other things are in your path?  Have you also had a look at the issue and seen if you can find any info relevant to you? https://github.com/fwcd/kotlin-language-server/issues/317.   That person has made it clear that they were able to fix exactly the same "Bad escape" errors by removing special characters from their project path. "Bad escape" is in 99.99 % of the cases only given in these situations.

**Comment by sova32** [comment]
Don't think that I'm just expressing dissatisfaction. I've been trying to
solve the issue all day and couldn't. That's why I decided to write to you.
Yes, I've sent multiple messages, but I provided all the information that
was written. Please clarify what information you need. I'm grateful for the
free add-on. Don't think poorly of me. I'm a good person. I'm not кussian!
I'm Ukrainian!

I'm sorry if I offended you in any way.

while i write this email i was delete all another plugins and reinstall
VSCode and it work! maby was conflict or someone corrupted in VSCode!
sorry! thank you! good luck!



вт, 8 авг. 2023 г. в 18:45, Marie Katrine Ekeberg ***@***.***

**Comment by themkat** [comment]
I think maybe there is a cultural barrier here then, and I may have overreacted 🙁 I'm not used to giving dissatisfaction in a blunt way. I may also have taken it a bit personally as I have contributed a lot to the language server 😆  


I'm very happy that you got it working! 😄 Hope me being a weirdo has not thrown you off continuing to look into this project!

**Comment by sova32** [comment]
You should be a bit more humble when people help you for free. Would not hurt at all. You take friendly suggestions in the worst way possible...

I didn't even intend to be rude. I just don't know your language well and I'm using a translator. I in no way meant to offend you, and I'm grateful for your assistance!

**Comment by sova32** [comment]
You not weirdo! 
You are a good man. We found a common language and this is a very valuable quality that we, Ukrainians, really appreciate.
I also want to express my deep gratitude from all Ukrainians to all of you and each of you for supporting Ukraine!
Take care of yourself!
sorry for my english.

**Comment by sova32** [comment]
good luck!
