### ISSUE TITLE
 server issue

### ISSUE THREAD

**Issue by starkingjs** [fwcd/vscode-kotlin#138]
Type: <b>Performance Issue</b>

Kotlin Language Client client: couldn't create connection to server.   Message: Pending response rejected since connection got disposed   Code: -32097

Extension version: 0.2.32
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A4-4350B R4, 5 COMPUTE CORES 2C+3G      (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (1.05GB free)|
|Process Argv|--crash-reporter-id b343486b-6778-4a03-adc9-438845f8d5a8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	    78	  1428	code main
    0	   172	   504	window [1] (Extension: Kotlin - Untitled (Workspace) - Visual Studio Code)
    0	    22	  4368	   utility-network-service
    0	    32	  6436	ptyHost
    0	    35	 10944	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\kstar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     5	 11852	     conpty-agent
    4	   152	  6900	   gpu-process
    0	    46	  8768	shared-process
    0	    18	 10644	   crashpad-handler
    0	    84	 11564	fileWatcher [1]
    5	    93	 11648	window [2] (Issue Reporter)
    0	   124	 12212	extensionHost [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by themkat** [comment]
Memory is the system seems very low, but maybe I'm misreading the system info section? The language server has many issues with extreme memory consumption, probably a mix of our own fault and the libraries we are using. https://github.com/fwcd/kotlin-language-server/issues/441 , https://github.com/fwcd/kotlin-language-server/issues/352


As always, it helps us a lot if you can upload your language server logs. 🙂  You find these in the Output-tab (usually in the bottom of VSCode), and the selection Kotlin:
<img width="961" alt="image" src="https://github.com/fwcd/vscode-kotlin/assets/5732795/ba0c14b4-fbe4-4937-9ad6-dcbc1fed5456">


My guess is that this is because of memory issues 🙁

**Comment by Hara1dDev** [comment]
Here is my log of the same issue: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/javacs/kt/MainKt has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
[Error - 8:09:53 PM] The Kotlin Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:09:53 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:09:53 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:09:53 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
