### ISSUE TITLE
Outline support 

### ISSUE THREAD

**Issue by srinikesh2929** [fwcd/vscode-kotlin#81]
### Motivation
I found that vs code is not able to identify the outlines such as fun main etc.

### Description
I would like to see the outlines of the code in my text

**Comment by Ceikry** [comment]
I believe this issue could benefit from further clarification, can I suggest adding a visual example of what you expect it to be doing, alongside a visual example of what it is doing?

**Comment by srinikesh2929** [comment]
![image](https://user-images.githubusercontent.com/76198579/144781311-f55b0273-85f6-47e1-ad05-641d6f3fb71f.png)
There are no outlines found by the extension, this feature was very useful in other languages(python,JS)

**Comment by fwcd** [comment]
Looks like the language server doesn't start. Would you mind pasting the output from `Output > Kotlin (from the dropdown)`?

**Comment by srinikesh2929** [comment]
I am confused what to paste... 
I am pasting the whole thing


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Info  - 9:10:52 AM] main      Adding script definitions [ScriptTemplateWithArgs]
[Info  - 9:10:52 AM] main      Kotlin Language Server: Version 1.2.0
[Info  - 9:10:52 AM] main      Connected to client
[Info  - 9:10:53 AM] client    Awaiting async termination...
[Info  - 9:10:53 AM] client    Awaiting debouncer termination...
[Info  - 9:10:53 AM] async0    Adding workspace folder kotlin development
[Info  - 9:10:53 AM] async0    Adding .../Dice-Roll/build.gradle.kts, .../Dice-Roll/settings.gradle.kts, .../kotlin/Main.kt, .../kotlin development/hello.kt under e:\Dev\kotlin development to source path
[Info  - 9:10:53 AM] async0    Searching for dependencies and Java sources in workspace root e:\Dev\kotlin development
[Info  - 9:10:53 AM] client    Awaiting async termination...
[Info  - 9:10:53 AM] async0    Resolving dependencies for 'Dice-Roll' through Gradle's CLI using tasks [kotlinLSPProjectDeps]...
Dec 10, 2021 9:10:53 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 9:10:53 AM] async0    Internal error: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:53 AM] java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Error - 9:10:53 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[Error - 9:10:53 AM] Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
[Error - 9:10:53 AM] 	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
[Error - 9:10:53 AM] 	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
[Error - 9:10:53 AM] 	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
[Error - 9:10:53 AM] 	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
[Error - 9:10:53 AM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
[Error - 9:10:53 AM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
[Error - 9:10:53 AM] 	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
[Error - 9:10:53 AM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[Error - 9:10:53 AM] 	... 3 more
[Error - 9:10:53 AM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 9:10:53 AM] Starting client failed
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more


 === Language Server Restart ===

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Info  - 9:10:57 AM] main      Adding script definitions [ScriptTemplateWithArgs]
[Info  - 9:10:57 AM] main      Kotlin Language Server: Version 1.2.0
[Info  - 9:10:57 AM] main      Connected to client
[Info  - 9:10:57 AM] async0    Adding workspace folder kotlin development
[Info  - 9:10:57 AM] async0    Adding .../Dice-Roll/build.gradle.kts, .../Dice-Roll/settings.gradle.kts, .../kotlin/Main.kt, .../kotlin development/hello.kt under e:\Dev\kotlin development to source path
[Info  - 9:10:57 AM] async0    Searching for dependencies and Java sources in workspace root e:\Dev\kotlin development
[Info  - 9:10:57 AM] async0    Resolving dependencies for 'Dice-Roll' through Gradle's CLI using tasks [kotlinLSPProjectDeps]...
Dec 10, 2021 9:10:57 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 9:10:57 AM] async0    Internal error: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:57 AM] java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Error - 9:10:57 AM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[Error - 9:10:57 AM] Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
[Error - 9:10:57 AM] 	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
[Error - 9:10:57 AM] 	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
[Error - 9:10:57 AM] 	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
[Error - 9:10:57 AM] 	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
[Error - 9:10:57 AM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
[Error - 9:10:57 AM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
[Error - 9:10:57 AM] 	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
[Error - 9:10:57 AM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[Error - 9:10:57 AM] 	... 3 more
[Error - 9:10:57 AM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Error - 9:10:57 AM] Starting client failed
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.javacs.kt.util.KotlinLSException: Could not find 'gradle' on PATH
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:69)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.getGradleCommand(GradleClassPathResolver.kt:67)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.readDependenciesViaGradleCLI(GradleClassPathResolver.kt:77)
	at org.javacs.kt.classpath.GradleClassPathResolverKt.access$readDependenciesViaGradleCLI(GradleClassPathResolver.kt:1)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspath(GradleClassPathResolver.kt:20)
	at org.javacs.kt.classpath.ClassPathResolver$DefaultImpls.getClasspathWithSources(ClassPathResolver.kt:29)
	at org.javacs.kt.classpath.GradleClassPathResolver.getClasspathWithSources(GradleClassPathResolver.kt:13)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:117)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more

[Info  - 9:10:57 AM] client    Awaiting async termination...
[Info  - 9:10:57 AM] client    Awaiting debouncer termination...
[Info  - 9:10:57 AM] client    Awaiting async termination...

**Comment by daplf** [comment]
Hey @srinikesh2929 

That output is helpful, thanks. From what I can tell, the language server fails because it can't find gradle on your PATH. The reason it looks for gradle is because the `Dice-Roll` folder contains a gradle project. I'm not sure what exactly you're trying to do, but I'm guessing your `hello.kt` file is unrelated to that gradle project. Adding gradle to your PATH will probably fix the issue with gradle, but if you're really trying to setup 2 unrelated projects in the same workspace, I'm not sure whether you'll get the language support you expect (I'm not sure the extension supports multiple projects in the same workspace properly)

**Comment by srinikesh2929** [comment]
@daplf  it's not working :(

**Comment by srinikesh2929** [comment]
> @daplf it's not working :(

Sorry it's working after a restart.
Thank you so much @daplf  and @fwcd

**Comment by andreszs** [comment]
No Kotlin plugin seems to be able to show the **OUTLINE** content so far. After synxtax highlighting, enabling the OUTLINE view should be plugin's **number 1 priority**, everything else is accessory.

Is there some clear step by step tutorial on how to make this work and/or why it's broken by default? 

![image](https://user-images.githubusercontent.com/10298071/172156577-dfec4a1c-9595-4376-b89c-6700134f2060.png)
